# Generated by Django 4.2.2 on 2023-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.IntegerField(verbose_name='ID del chat extraido')),
                ('mensaje', models.TextField(verbose_name='Mensaje recibido de API de Chat')),
                ('resultado', models.TextField(verbose_name='Resultado del código')),
            ],
        ),
    ]
